### ISSUE TITLE
GeoMesa downloads attempted even when disabled

### ISSUE THREAD

**Issue by tkunicki** [ccri/cloud-local#45]
A failed download dropped a 0 byte geomesa jar in `${ACCUMULO_HOME}/lib/ext`.  `pkg_geomesa-*` vars were commented out.

2 issues here:

1. don't attempt download if needed vars are unset
2. don't leave traces of failed downloads (a general cloud-local issue)

**Comment by djr7m** [comment]
This does indeed appear to be fixed in the current version I'm working with.
