### ISSUE TITLE
Add better package cacheing

### ISSUE THREAD

**Issue by nhambletCCRI** [ccri/cloud-local#52]
The pkgs folder works ok for an existing cloud-local, but scripting up bits of top of cloud-local could be improved by a more global storage place than a particular install. One's ~/.m2/repo seems like a good place. If necessary, we could even deploy com.ccri.cloud-local:xyz:v artifacts for the things we download from mirrors. But if there's a different package cacheing proposal, that's fine too.

**Comment by djr7m** [comment]
One immediate work-around.
`cd cloud-local; rm pkg; ln -s /net/synds1/volume2/projects2/cloud-local/packages pkg`

**Comment by djr7m** [comment]
fixed as of 5cc425ec4cd81cea5dc6dcfef1f2adf9f1e5c97d
Just set an http proxy (internal to CCRi use squid.ccri.com port 3128)
